added retry to destroy

diff --git a/.github/actions/destroy-infrastructure/action.yaml b/.github/actions/destroy-infrastructure/action.yaml
--- a/.github/actions/destroy-infrastructure/action.yaml
+++ b/.github/actions/destroy-infrastructure/action.yaml
@@ -1,5 +1,5 @@
-name: 'Terraform Infrastructure Creation'
-description: 'Initialize and apply Terraform configuration'
+name: 'Terraform Infrastructure destroy'
+description: 'Initialize and destroy Terraform configuration'
 
 inputs:
   applicationsList:
@@ -57,16 +57,38 @@ runs:
       working-directory: ${{ inputs.workingDirectory }}
       shell: bash
 
-    - name: Terraform Destroy
+    - name: Terraform Destroy with Retry
       run: |
-        terraform destroy \
-          -auto-approve \
-          -var 'applications_list=${{ inputs.applicationsList }}' \
-          -var "cluster_name=${{ inputs.clusterName }}" \
-          -var "kubeconfig_path=${{ inputs.kubeconfigPath }}" \
-          -var "path=argocd/${{ inputs.environment }}" \
-          -var "repo_url=${{ inputs.repoUrl }}" \
-          -var "target_revision=${{ inputs.branch }}"
+        MAX_RETRIES=5
+        DELAY=30
+        retry_count=0
+
+        # Loop until the maximum number of retries is reached
+        until [ $retry_count -ge $MAX_RETRIES ]
+        do
+          # Attempt to perform terraform destroy
+          terraform destroy -auto-approve \
+            -var 'applications_list=${{ inputs.applicationsList }}' \
+            -var "cluster_name=${{ inputs.clusterName }}" \
+            -var "kubeconfig_path=${{ inputs.kubeconfigPath }}" \
+            -var "path=argocd/${{ inputs.environment }}" \
+            -var "repo_url=${{ inputs.repoUrl }}" \
+            -var "target_revision=${{ inputs.branch }}"
+          exit_code=$?
+
+          # Check if the destroy was successful
+          if [ $exit_code -eq 0 ]; then
+            echo "Terraform destroy completed successfully."
+            exit 0
+          else
+            echo "Terraform destroy failed. Retrying in $DELAY seconds..."
+            retry_count=$((retry_count+1))
+            sleep $DELAY
+          fi
+        done
+
+        echo "Terraform destroy failed after $MAX_RETRIES attempts."
+        exit 1
       env:
         AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
         AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
